# This is a basic workflow to help you get started with Actions

name: CI trigger

on:
  workflow_dispatch:
    inputs:
      text:
        required: true
        type: string
        
jobs:
  reusable_workflow_job:
    uses: ./.github/workflows/sub.yml
    with:
      text: ${{ inputs.text }}
  xxx:
    runs-on: ubuntu-latest
    needs: [reusable_workflow_job]
    steps:
      - name: xxx
        run: echo xxx
   
