# This is a basic workflow to help you get started with Actions

name: CI trigger

on:
  workflow_dispatch:
    inputs:
      text:
        required: true
        type: string
env:
  VERSION: ${inputs.text%-*}
  RELEASE_TYPE: ${inputs.text#*-}


        
jobs:
  

  reusable_workflow_job:
    uses: ./.github/workflows/sub.yml
    with:
      tag: ${{ inputs.text }}
