# This is a basic workflow to help you get started with Actions

name: CI trigger

on:
  workflow_dispatch:

env:
  VERSION: "1.1.1.1_1114"

        
jobs:
  aa:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${VERSION}
          echo ${VERSION%-*}
          echo ${{env.VERSION}}
      
