name: Mark release as deleted in CRM
on:
    release:
        types: [ deleted ]

jobs:
    parse_version:
        name: parse_version
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.parse_version.outputs.version }}
        steps:
          - id: parse_version
            run: |
                ref=${{github.ref}} 
                tag=${ref#refs/tags/}
                version=${tag%-*} 
                echo "::set-output name=version::$version"
    mark_as_deleted:
        needs: parse_version
        uses: filipagh/shopper/.github/workflows/sub.yml@master
        with:
            version: ${{needs.parse_version.outputs.version}}
        secrets: inherit
