# This is a basic workflow to help you get started with Actions

name: CI trigger

on:
  workflow_dispatch:
    inputs:
      text:
        required: true
        type: string
env:
  VERSION: ${input%-*}
  RELEASE_TYPE: ${input#*-}


        
jobs:
  reusable_workflow_job:
    uses: ./.github/workflows/sub.yml
    with:
      text: ${{ inputs.text }}
  xxx:
    if: ${{env.RELEASE_TYPE == ""}}
    strategy:
      matrix: 
        variable: ['a','b']
    runs-on: ubuntu-latest
    needs: [reusable_workflow_job]
    steps:
      - name: xxx
        run: echo ${{ matrix.variable }}
   
