name: Mark release as deleted in CRM
on:
    release:
        types: [ created ]

    # remove postfix from version

jobs:
    mark_as_deleted:
        uses: filipagh/shopper/.github/workflows/sub.yml@master
        with:
            version: "1111"
        secrets: inherit
