name: Mark release as deleted in CRM

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string

jobs:
    mark_as_deleted:
        name: mark_as_deleted
        runs-on: ubuntu-latest
        steps:
      

          - name: process_version
            run: |
              echo ${{inputs.text}}
              echo ${{$GITHUB_REF}}
          
