
name: CI

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  parse_tag:
    outputs:
      version: ${{}}
      build_type: ${{}}
    runs-on: ubuntu-latest
    steps:
      - name: process_version
        run: |
          echo ${{inputs.text}}
          echo "::set-output version=${{inputs.text}}%-*"

