
name: CI

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string

jobs:
  xxx:
    runs-on: ubuntu-latest
    steps:
      - name: xx
        run: |
          echo ${{inputs.text}}

