name: Mark release as deleted in CRM

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
                              

jobs:
    mark_as_deleted:
        name: mark_as_deleted
        runs-on: ubuntu-latest
        steps:
          - name: proces
            run: |
                ref=${{inputs.version}} 
                tag=${ref#refs/tags/}
                version=${tag%-*} 
                echo "tt=$version" >> $GITHUB_ENV
    proces:
        needs: mark_as_deleted
        strategy:
          fail-fast: false
          matrix:
            product: [ b229622b, intwkla1, ladeskcz, spinla01, qusuppla ]
        name: proces
        runs-on: ubuntu-latest
        steps: 
          - name: process_version
            run: |
              echo "${{inputs.version}}"
              echo "${{github.ref}}"
              echo "${{env.tt}}"
              echo "${{ matrix.product }}"

          
